import { ClientData } from '../types'

export const denverPlumbingProsData: ClientData = {
  business: {
    id: 'denver-plumbing-pros',
    name: 'Denver Plumbing Pros',
    slug: 'denver-plumbing-pros',
    industry: 'Plumbing',
    description: 'Professional plumbing services in Denver and surrounding areas. We provide emergency repairs, installations, and maintenance with 24/7 availability. Our licensed and insured team has been serving the Denver metro area for over 10 years.',
    services: ['Emergency Plumbing', 'Water Heater Installation', 'Drain Cleaning', 'Pipe Repair', 'Bathroom Remodeling', 'Kitchen Plumbing', 'Commercial Plumbing'],
    phone: '(303) 555-0123',
    email: 'info@denverplumbingpros.com',
    website: 'https://denverplumbingpros.com',
    rating: 4.8,
    reviewCount: 127,
    isActive: true,
    heroImage: '/placeholder.svg?height=400&width=600&text=Denver+Plumbing+Pros',
    yearEstablished: 2015,
    employeeCount: '15-25',
    specialties: ['Emergency Repairs', '24/7 Service', 'Commercial Plumbing', 'Water Heater Specialists'],
    emergencyService: true,
    serviceRadius: '25 miles',
    certifications: ['Licensed Plumber', 'Bonded & Insured', 'BBB A+ Rating', 'Master Plumber Certified'],
    hq: {
      address: '1234 Main Street',
      city: 'Denver',
      state: 'CO',
      zipCode: '80202',
      phone: '(303) 555-0123',
      email: 'info@denverplumbingpros.com',
      hours: {
        'Monday': '7:00 AM - 6:00 PM',
        'Tuesday': '7:00 AM - 6:00 PM',
        'Wednesday': '7:00 AM - 6:00 PM',
        'Thursday': '7:00 AM - 6:00 PM',
        'Friday': '7:00 AM - 6:00 PM',
        'Saturday': '8:00 AM - 4:00 PM',
        'Sunday': 'Emergency Only'
      }
    }
  },
  serviceAreas: [
    {
      id: 'denver-plumbing',
      name: 'Denver',
      slug: 'denver-plumbing',
      city: 'Denver',
      state: 'CO',
      description: 'Professional plumbing services in Denver, Colorado. 24/7 emergency response for all your plumbing needs including repairs, installations, and maintenance.',
      businessId: 'denver-plumbing-pros',
      services: ['Emergency Plumbing', 'Water Heater Installation', 'Drain Cleaning', 'Pipe Repair'],
      serviceRadius: '25 miles',
      localKeywords: [
        'plumber denver',
        'denver plumbing services',
        'emergency plumber denver',
        'water heater repair denver',
        'drain cleaning denver'
      ],
      population: 715522,
      county: 'Denver County',
      zipCodes: ['80202', '80203', '80204', '80205', '80206'],
      localEmail: 'denver@denverplumbingpros.com',
      monthlyTraffic: '2.4K',
      rankingKeywords: 15,
      rating: 4.8,
      reviewCount: 45,
      citation: {
        businessName: 'Denver Plumbing Pros',
        address: '1234 Main Street, Denver, CO 80202',
        phone: '(303) 555-0123',
        website: 'https://denverplumbingpros.com',
        services: ['Emergency Plumbing', 'Water Heater Installation', 'Drain Cleaning', 'Pipe Repair'],
        isActive: true
      }
    },
    {
      id: 'aurora-plumbing',
      name: 'Aurora',
      slug: 'aurora-plumbing',
      city: 'Aurora',
      state: 'CO',
      description: 'Reliable plumbing services in Aurora, Colorado. From emergency repairs to new installations, we serve Aurora residents with professional plumbing solutions.',
      businessId: 'denver-plumbing-pros',
      services: ['Emergency Plumbing', 'Water Heater Services', 'Bathroom Remodeling', 'Commercial Plumbing'],
      serviceRadius: '20 miles',
      localKeywords: [
        'plumber aurora co',
        'aurora plumbing services',
        'emergency plumber aurora',
        'bathroom remodeling aurora',
        'commercial plumbing aurora'
      ],
      population: 386261,
      county: 'Arapahoe County',
      zipCodes: ['80010', '80011', '80012', '80013', '80014'],
      localEmail: 'aurora@denverplumbingpros.com',
      monthlyTraffic: '1.8K',
      rankingKeywords: 12,
      rating: 4.7,
      reviewCount: 38,
      citation: {
        businessName: 'Denver Plumbing Pros - Aurora',
        address: '5678 Aurora Ave, Aurora, CO 80010',
        phone: '(303) 555-0124',
        website: 'https://denverplumbingpros.com/aurora',
        services: ['Emergency Plumbing', 'Water Heater Services', 'Bathroom Remodeling', 'Commercial Plumbing'],
        isActive: true
      }
    },
    {
      id: 'lakewood-plumbing',
      name: 'Lakewood',
      slug: 'lakewood-plumbing',
      city: 'Lakewood',
      state: 'CO',
      description: 'Expert plumbing services in Lakewood, Colorado. Serving residential and commercial customers with quality plumbing repairs and installations.',
      businessId: 'denver-plumbing-pros',
      services: ['Residential Plumbing', 'Kitchen Plumbing', 'Water Heater Installation', 'Drain Cleaning'],
      serviceRadius: '15 miles',
      localKeywords: [
        'plumber lakewood co',
        'lakewood plumbing repair',
        'kitchen plumbing lakewood',
        'water heater lakewood',
        'residential plumber lakewood'
      ],
      population: 155984,
      county: 'Jefferson County',
      zipCodes: ['80214', '80215', '80226', '80227', '80228'],
      localEmail: 'lakewood@denverplumbingpros.com',
      monthlyTraffic: '1.2K',
      rankingKeywords: 10,
      rating: 4.9,
      reviewCount: 29,
      citation: {
        businessName: 'Denver Plumbing Pros - Lakewood',
        address: '9012 Lakewood Blvd, Lakewood, CO 80214',
        phone: '(303) 555-0125',
        website: 'https://denverplumbingpros.com/lakewood',
        services: ['Residential Plumbing', 'Kitchen Plumbing', 'Water Heater Installation', 'Drain Cleaning'],
        isActive: true
      }
    }
  ],
  articles: [
    {
      id: 'emergency-plumbing-denver-guide',
      title: 'Emergency Plumbing Services in Denver: Complete Guide 2024',
      slug: 'emergency-plumbing-denver-guide',
      excerpt: 'When plumbing emergencies strike in Denver, knowing what to do can save you thousands. Our comprehensive guide covers 24/7 emergency services, costs, and prevention tips.',
      content: 'Full article content about emergency plumbing services in Denver...',
      category: 'Emergency Services',
      tags: ['emergency plumbing', 'denver', 'water damage', '24/7 service'],
      date: '2024-01-15',
      readTime: '8 min read',
      views: 1250,
      author: 'Local Service Near You',
      image: '/placeholder.svg?height=300&width=500&text=Emergency+Plumbing+Denver',
      featured: true,
      type: 'client',
      clientName: 'Denver Plumbing Pros',
      clientSlug: 'denver-plumbing-pros',
      backlinks: ['https://denverplumbingpros.com'],
      serviceAreaId: 'denver-plumbing',
      publishedAt: '2024-01-15T10:00:00Z'
    },
    {
      id: 'water-heater-installation-aurora',
      title: 'Water Heater Installation in Aurora, CO: Expert Guide & Costs',
      slug: 'water-heater-installation-aurora',
      excerpt: 'Need a new water heater in Aurora? Learn about installation costs, best brands, and why professional installation matters for Aurora homeowners.',
      content: 'Full article content about water heater installation in Aurora...',
      category: 'Water Heater Services',
      tags: ['water heater', 'aurora', 'installation', 'costs'],
      date: '2024-01-12',
      readTime: '6 min read',
      views: 890,
      author: 'Local Service Near You',
      image: '/placeholder.svg?height=300&width=500&text=Water+Heater+Aurora',
      featured: false,
      type: 'client',
      clientName: 'Denver Plumbing Pros',
      clientSlug: 'denver-plumbing-pros',
      backlinks: ['https://denverplumbingpros.com/aurora'],
      serviceAreaId: 'aurora-plumbing',
      publishedAt: '2024-01-12T14:00:00Z'
    },
    {
      id: 'kitchen-plumbing-lakewood',
      title: 'Kitchen Plumbing Services in Lakewood: Repairs & Remodeling',
      slug: 'kitchen-plumbing-lakewood',
      excerpt: 'Planning a kitchen remodel in Lakewood? Our guide covers everything from sink installation to garbage disposal repairs by local plumbing experts.',
      content: 'Full article content about kitchen plumbing in Lakewood...',
      category: 'Kitchen Plumbing',
      tags: ['kitchen plumbing', 'lakewood', 'remodeling', 'sink installation'],
      date: '2024-01-10',
      readTime: '7 min read',
      views: 654,
      author: 'Local Service Near You',
      image: '/placeholder.svg?height=300&width=500&text=Kitchen+Plumbing+Lakewood',
      featured: false,
      type: 'client',
      clientName: 'Denver Plumbing Pros',
      clientSlug: 'denver-plumbing-pros',
      backlinks: ['https://denverplumbingpros.com/lakewood'],
      serviceAreaId: 'lakewood-plumbing',
      publishedAt: '2024-01-10T09:00:00Z'
    }
  ]
}
